Fixed Broken Xamarin.com URL references
xamarin/Xamarin.Forms-api-docs pull request #236
Opened 2020-10-18 19:13 UTC by saamerm

* Fixed all remaining broken URL references to Xamarin.com
* Fixed the URL in a lot of places where users looking for Xamarin Samples are taken to the right place
* Ensured that all the Deep Linking URL was correct and that the Title of the article matched the text inside the <a href> tag
* Fixed the behaviors URLs to take users to the right place
* Fixed the Intro to Data Binding link to go to the blog
* Fixed the link for the Xamarin Forms Images reference
* Fixed the Image source in the examples to take display a Xamarin PNG that actually works, since all other pngs were of different formats that may not have worked
* Corrected the webview example, so that users dont get an error on android when they are trying to go to the older blog.xamarin.com

**Testing**
----------
* Ensured that these were actual issues by going to the docs page for behaviors and seeing that it in fact have the wrong URL and took users to the wrong place

2020-10-18 19:14 UTC, opbld30 commented
Docs Build status updates of commit _[2df2c7b](https://github.com/saamerm/Xamarin.Forms-api-docs/commits/2df2c7bba19a88bed0588bc1a85540ca59dbcdb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Xamarin.Forms/AbsoluteLayout.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/AbsoluteLayout.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/AppLinkEntry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/AppLinkEntry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Application.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Application.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Behavior.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Behavior.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Behavior`1.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Behavior%601.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/BindableProperty.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/BindableProperty.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Button.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Button.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Cell.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Cell.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/ContentPage.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ContentPage.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Entry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Entry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/IAppLinkEntry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IAppLinkEntry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/IAppLinks.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IAppLinks.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Image.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Image.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/ImageCell.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ImageCell.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Label.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Label.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/StackLayout.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/StackLayout.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/TabbedPage.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/TabbedPage.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/WebView.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/WebView.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C18%5C255ca139-136e-0e83-7663-6efcfaf1b793%5CPullRequest%5C202010181913235992-236%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oEvKHe08geEs0oWag7i2EgJtUtzDm2smhLV0jd3huEw%3D&st=2020-10-18T19%3A09%3A40Z&se=2020-11-18T19%3A14%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/255ca139-136e-0e83-7663-6efcfaf1b793?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 15:10 UTC, opbld32 commented
Docs Build status updates of commit _[9b7a961](https://github.com/saamerm/Xamarin.Forms-api-docs/commits/9b7a961965aece93dc0516c6fa5774536f610f97)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Xamarin.Forms/AbsoluteLayout.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/AbsoluteLayout.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/AppLinkEntry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/AppLinkEntry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Application.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Application.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Behavior.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Behavior.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Behavior`1.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Behavior%601.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Button.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Button.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Cell.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Cell.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Entry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Entry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/IAppLinkEntry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IAppLinkEntry.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/IAppLinks.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/IAppLinks.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Image.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Image.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/ImageCell.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/ImageCell.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/Label.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Label.xml) | :white_check_mark:Succeeded | |
[docs/Xamarin.Forms/WebView.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/WebView.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C255ca139-136e-0e83-7663-6efcfaf1b793%5CPullRequest%5C202010211509198172-236%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m8rwAS%2BqDtr9BrIDFFoiApiPcmHCEcv%2FAi0KpX8YDzI%3D&st=2020-10-21T15%3A05%3A39Z&se=2020-11-21T15%3A10%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/255ca139-136e-0e83-7663-6efcfaf1b793?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 15:45 UTC, saamerm commented
@Redth looks good to me. @samhouts, any comments?

2020-10-21 23:15 UTC, samhouts approved these changes

2020-10-30 19:26 UTC, rachelkang requested changes
See suggestions/comments - remove locales from all URLs and change URL for sample apps to All Samples page https://docs.microsoft.com/en-us/samples/browse/?products=xamarin&term=Xamarin.Forms&terms=Xamarin.Forms

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Behavior.xml
> +    <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/">Xamarin.Forms Behaviors</related>
```suggestion
    <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/behaviors/">Xamarin.Forms Behaviors</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Behavior`1.xml
> +    <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/behaviors/">Xamarin.Forms Behaviors</related>
```suggestion
    <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/behaviors/">Xamarin.Forms Behaviors</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Button.xml
> +        <block type="note">To display the <c>icon.png</c> image with the above XAML, the developer must place it in the appropriate location, with the appropriate build action, specific to each platf
```suggestion
        <block type="note">To display the <c>icon.png</c> image with the above XAML, the developer must place it in the appropriate location, with the appropriate build action, specific to each platform project. The <format type="text/html"><a href="https://docs.microsoft.com/xamarin/xamarin-forms/user-interface/images">Images</a></format> topic explains this and other important details about working with images in Xamarin.Forms.</block>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Entry.xml
> +        <para>The FormsGallery sample, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/samples/" target="_blank">Sample Applications
These links point to both the specific example, and the more general page with all the XF samples :)
```suggestion
        <para>The <format type="text/html"><a href="https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/formsgallery/" target="_blank">FormsGallery sample</a></format>, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/samples/browse/?products=xamarin&term=Xamarin.Forms&terms=Xamarin.Forms" target="_blank">Sample Applications</a></format> page, has an EntryDemoPage.cs file. This file contains a more complete example.</para>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +    <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
    <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinkEntry.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinks.xml
> +    <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
    <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinks.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinks.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/IAppLinks.xml
> +        <related type="article" href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```suggestion
        <related type="article" href="https://docs.microsoft.com/xamarin/xamarin-forms/app-fundamentals/deep-linking">Application Indexing and Deep Linking</related>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Image.xml
> +      <para>The FormsGallery sample, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/samples/" target="_blank">Sample Applications</
As before - these links point to both the specific example, and the more general page with all the XF samples :)
```suggestion
      <para>The <format type="text/html"><a href="https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/formsgallery/" target="_blank">FormsGallery sample</a></format>, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/samples/browse/?products=xamarin&term=Xamarin.Forms&terms=Xamarin.Forms" target="_blank">Sample Applications</a></format> page, has an ImageDemoPage.cs file. This file contains a longer and more complete example.</para>
```

2020-10-30 19:26 UTC, rachelkang commented on docs/Xamarin.Forms/Label.xml
> +        <para>The FormsGallery sample, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/en-us/xamarin/xamarin-forms/samples/" target="_blank">Sample Applications
As before - these links point to both the specific example, and the more general page with all the XF samples :)
```suggestion
        <para>The <format type="text/html"><a href="https://docs.microsoft.com/samples/xamarin/xamarin-forms-samples/formsgallery/" target="_blank">FormsGallery sample</a></format>, which can be found on the <format type="text/html"><a href="https://docs.microsoft.com/samples/browse/?products=xamarin&term=Xamarin.Forms&terms=Xamarin.Forms" target="_blank">Sample Applications</a></format> page, has a LabelDemoPage.cs file. This file contains a longer and more complete example.</para>
```

2020-10-30 20:03 UTC, opbld34 commented
Docs Build status updates of commit _[52c0060](https://github.com/saamerm/Xamarin.Forms-api-docs/commits/52c0060004a19563b630a1afd3c6366008d0bfa6)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-10-30 20:04 UTC, saamerm commented
@rachelkang good suggestions. Made the changes

2020-10-30 20:04 UTC, opbld32 commented
Docs Build status updates of commit _[52c0060](https://github.com/saamerm/Xamarin.Forms-api-docs/commits/52c0060004a19563b630a1afd3c6366008d0bfa6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Xamarin.Forms/Entry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Entry.xml) | :x:Error | | [Details](#user-content-6ec33f27-ace771e8)
[docs/Xamarin.Forms/Image.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Image.xml) | :x:Error | | [Details](#user-content-5e265e01-ace771e8)
[docs/Xamarin.Forms/Label.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Label.xml) | :x:Error | | [Details](#user-content-ae8c0e16-ace771e8)
[]() | :x:Error | | [Details](#user-content-ace771e8)

<a id="6ec33f27-ace771e8"></a>
### [docs/Xamarin.Forms/Entry.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Entry.xml)
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_InternalError]** 
`````
Intenal Several Error: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 59, position 307.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ECMA2Yaml.ECMALoader.LoadType(FileItem typeFile)
   at ECMA2Yaml.ECMALoader.LoadTypes(String basePath, Namespace ns)
`````

<a id="5e265e01-ace771e8"></a>
### [docs/Xamarin.Forms/Image.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Image.xml)
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_InternalError]** 
`````
Intenal Several Error: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 56, position 305.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ECMA2Yaml.ECMALoader.LoadType(FileItem typeFile)
   at ECMA2Yaml.ECMALoader.LoadTypes(String basePath, Namespace ns)
`````

<a id="ae8c0e16-ace771e8"></a>
### [docs/Xamarin.Forms/Label.xml](https://github.com/saamerm/Xamarin.Forms-api-docs/blob/master/docs/Xamarin.Forms/Label.xml)
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_InternalError]** 
`````
Intenal Several Error: System.Xml.XmlException: '=' is an unexpected token. The expected token is ';'. Line 63, position 307.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(Int32 pos, String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Parse(String text, LoadOptions options)
   at ECMA2Yaml.ECMALoader.LoadType(FileItem typeFile)
   at ECMA2Yaml.ECMALoader.LoadTypes(String basePath, Namespace ns)
`````

<a id="ace771e8"></a>
###
 - **Line 0, Column 0**: **[Error-ECMA2Yaml_File_LoadFailed]** `````Failed to load 3 files, aborting...`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C30%5C255ca139-136e-0e83-7663-6efcfaf1b793%5CPullRequest%5C202010302003372566-236%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VvNhK6MaEcZLk0K%2FxK1NFt4Dxx7u2MC9E3W9Stfd%2FW4%3D&st=2020-10-30T19%3A59%3A30Z&se=2020-11-30T20%3A04%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/255ca139-136e-0e83-7663-6efcfaf1b793?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-31 14:54 UTC, saamerm commented
@samhouts the errors in question seem to be from urls that work fine. What can we do?

2020-10-31 17:55 UTC, rachelkang commented on docs/Xamarin.Forms/ImageCell.xml
> +                                Device.OnPlatform(ImageSource.FromUri(new Uri("https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/xamarin/xamarin.png")),
Would you also swap out the image url to this one from our dotnet swag repo? Thanks :)
https://github.com/dotnet-foundation/swag/tree/master/xamarin

2024-01-29 09:15 UTC, davidbritch commented
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any PRs for the .NET MAUI API docs should be opened in that repository.

2024-01-29 09:15 UTC, closed without merging