Update ReferenceExtension.xml
xamarin/Xamarin.Forms-api-docs pull request #261
Opened 2020-10-21 17:17 UTC by mattleibow

2020-10-21 17:19 UTC, opbld32 commented
Docs Build status updates of commit _[aff5d1c](https://github.com/xamarin/Xamarin.Forms-api-docs/commits/aff5d1cef70131c8114f72e31d964edcd9a2dc20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Xamarin.Forms.Xaml/ReferenceExtension.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/mattleibow/fix-the-fix/docs/Xamarin.Forms.Xaml/ReferenceExtension.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C255ca139-136e-0e83-7663-6efcfaf1b793%5CPullRequest%5C202010211717478986-261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gsCjgPt6%2FvNPvh9irp5scQSUmf1tB72fZMS1wiH3BEY%3D&st=2020-10-21T17%3A14%3A09Z&se=2020-11-21T17%3A19%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/255ca139-136e-0e83-7663-6efcfaf1b793?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 18:59 UTC, opbld32 commented
Docs Build status updates of commit _[25df4b7](https://github.com/xamarin/Xamarin.Forms-api-docs/commits/25df4b7a59e00b08a912b911f4921487c1bcd79e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/Xamarin.Forms.Xaml/ReferenceExtension.xml](https://github.com/xamarin/Xamarin.Forms-api-docs/blob/mattleibow/fix-the-fix/docs/Xamarin.Forms.Xaml/ReferenceExtension.xml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C10%5C21%5C255ca139-136e-0e83-7663-6efcfaf1b793%5CPullRequest%5C202010211858173876-261%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oAkA2FvmDmFhxI%2BGPjNJRop3YeuI6Iqk8X7hFS9FM5c%3D&st=2020-10-21T18%3A54%3A39Z&se=2020-11-21T18%3A59%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/255ca139-136e-0e83-7663-6efcfaf1b793?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-10-21 23:16 UTC, samhouts approved these changes

2020-10-22 07:29 UTC, StephaneDelcroix commented on docs/Xamarin.Forms.Xaml/ReferenceExtension.xml
> +This should be used as a compile time `{x:Reference Name}` reference.
```suggestion
x:Reference provides XAML language-level support for element reference.
```

2020-10-22 07:29 UTC, StephaneDelcroix requested changes
see comment

2024-01-29 09:15 UTC, davidbritch commented
[Microsoft support for Xamarin](https://dotnet.microsoft.com/en-us/platform/support/policy/xamarin) will end on May 1, 2024 for all Xamarin SDKs including Xamarin.Forms. In preparation for this, all issues and PRs in this repository are being closed.

.NET MAUI is the replacement for Xamarin.Forms, and its API docs are built from /// in the [dotnet/maui](https://github.com/dotnet/maui) repository. Therefore, any PRs for the .NET MAUI API docs should be opened in that repository.

2024-01-29 09:15 UTC, closed without merging